before_script:
- export SCRAM_ARCH=slc6_amd64_gcc630
- source /cvmfs/cms.cern.ch/cmsset_default.sh
- cd /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_1/
- eval `scramv1 runtime -sh`
- cd -
- source setenv.sh

EXO16052:
  tags:
  - cvmfs
  script:
  - cd EXO-16-052
  - python ./write_yaml.py

EXO16056:
  tags:
  - cvmfs
  script:
  - cd EXO-16-056
  - python ./write_yaml.py
